version: "2"
linters:
  enable:
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
  disable:
    - errcheck
    - gocritic
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
