issues:
  exclude-use-default: false
  max-same-issues: 0

linters:
  enable:
    - stylecheck
    - unconvert
    - gofmt
    - misspell
    - unparam
    - nakedret
    - prealloc
    - misspell
  disable:
    - errcheck
    - gocritic