---
project_name: nats-surveyor

release:
  draft: true
  github:
    owner: snappcloud
    name: nats-surveyor

  name_template: 'Release {{.Tag}}'

builds:
  - main: .
    id: nats-surveyor
    binary: nats-surveyor
    ldflags:
      - "-s -w -X github.com/nats-io/nats-surveyor/cmd.Version={{ .Tag }}"
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    - windows
    goarch:
    - 386
    - amd64
    - arm
    - arm64
    goarm:
    - 6
    - 7
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - id: zipfiles
    wrap_in_directory: true
    name_template: '{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm
      }}v{{ .Arm }}{{ end }}'
    format: zip
    files:
    - LICENSE
    - README.md
    - nats-surveyor*

nfpms:
  - formats:
      - deb
    file_name_template: '{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm
      }}v{{ .Arm }}{{ end }}'
    bindir: /usr/local/bin
    description: A Simplified Prometheus Monitoring Solution for NATS
    vendor: nats.io
    maintainer: Colin Sullivan <colin@nats.io>
    homepage: https://nats.io
    license: Apache 2.0

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: '{{ .ProjectName }}-v{{ .Version }}-checksums.txt'
