{
 "title": "Clusters",
 "tags": [ "surveyor" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prom_ds", "label": "Prometheus Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(nats_core_info, server_cluster)"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(nats_core_gateway_count)", "legendFormat": "Clusters" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nats_core_info{server_cluster=~\"$cluster\"}) ",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Cluster Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nats_core_route_sent_bytes{server_cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(nats_core_route_recv_bytes{server_cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Cluster Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nats_core_route_sent_msg_count{server_cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(nats_core_route_recv_msg_count{server_cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Cluster Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages Sent",
     "type": "graph",
     "description": "Messages sent for each route",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "messages / sec" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_route_sent_msg_count{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "Server {{server_name}} - Route {{server_route_name}}"
      }
     ]
    },
    {
     "title": "Messages Received",
     "type": "graph",
     "description": "Messages received for each route",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "messages / sec" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_route_recv_msg_count{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "Server {{server_name}} - Route {{server_route_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Sent",
     "type": "graph",
     "description": "Bytes sent for each route",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "Bps", "label": "bytes / sec" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_route_sent_bytes{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "Server {{server_name}} - Route {{server_route_name}}"
      }
     ]
    },
    {
     "title": "Bytes Received",
     "type": "graph",
     "description": "Bytes received for each route",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "Bps", "label": "bytes / sec" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_route_recv_bytes{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "Server {{server_name}} - Route {{server_route_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending Data",
     "type": "graph",
     "description": "Data in the pending buffers that needs to be sent to remotes",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "nats_core_route_pending_bytes{server_cluster=~\"$cluster\"}",
       "legendFormat": "Server {{server_name}} - Route {{server_route_name}}"
      }
     ]
    },
    {
     "title": "Cluster Size",
     "type": "graph",
     "description": "The number of servers in each cluster",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "cluster size" }
     ],
     "targets": [
      {
       "expr": "sum(nats_core_info{server_cluster=~\"$cluster\"}) by (server_cluster)",
       "legendFormat": "{{server_cluster}}"
      }
     ]
    }
   ]
  }
 ]
}