{
 "title": "NATS Surveyor",
 "tags": [ "surveyor" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prom_ds", "label": "Prometheus Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(nats_core_info, server_cluster)"
    }
   },
   {
    "name": "expected",
    "query": {
     "query": "query_result(nats_survey_expected_count)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Received Messages",
   "type": "stat",
   "description": "Aggregate messages received by all servers from clients, routes, gateways and leafnodes",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nats_core_recv_msgs_count{server_cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Sent Messages",
   "type": "stat",
   "description": "Aggregate messages sent by all servers to clients, routes, gateways and leafnodes",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nats_core_sent_msgs_count{server_cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "stat",
   "description": "Aggregate bytes received by all servers from clients, routes, gateways and leafnodes",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nats_core_recv_bytes{server_cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "stat",
   "description": "Aggregate bytes sent by all servers to clients, routes, gateways and leafnodes",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nats_core_sent_bytes{server_cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "description": "Total current connections across all servers",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_core_connection_count{server_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "stat",
   "description": "Slow consumers seen per second",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nats_core_slow_consumer_count{server_cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Slow"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "stat",
   "description": "Number of known clusters",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(nats_core_info{server_cluster=~\"$cluster\"}) by (server_cluster))",
     "legendFormat": "Servers"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "stat",
   "description": "Number of known servers",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nats_core_info{server_cluster=~\"$cluster\"})",
     "legendFormat": "Servers"
    }
   ]
  },
  {
   "title": "Route Connections",
   "type": "stat",
   "description": "Number of routes reported as active",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_core_route_count{server_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Gateway Connections",
   "type": "stat",
   "description": "Number of routes reported as active",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_core_gateway_count{server_cluster=~\"$cluster\"})",
     "legendFormat": "Gateways"
    }
   ]
  },
  { "title": "JetStream Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "JS Filestore",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_core_jetstream_filestore_size_bytes{})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(nats_core_jetstream_filestore_used_bytes{})",
     "legendFormat": "Consumed"
    },
    {
     "expr": "sum(nats_core_jetstream_filestore_reserved_bytes{})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "JS Memstore",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_core_jetstream_memstore_size_bytes{})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(nats_core_jetstream_memstore_used_bytes{})",
     "legendFormat": "Consumed"
    },
    {
     "expr": "sum(nats_core_jetstream_memstore_reserved_bytes{})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "JS  Domains",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by(server_domain) (nats_core_jetstream_info{server_jetstream=\"true\"})",
     "legendFormat": "{{server_domain}}"
    }
   ]
  },
  {
   "title": "JS  Meta-Leader",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nats_core_jetstream_cluster_raft_group_leader * on(server_id) group_left(server_cluster,server_name, server_domain) nats_core_jetstream_info) > 0",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "JS  Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by(server_cluster) (nats_core_jetstream_info{server_jetstream=\"true\"}))"
    }
   ]
  },
  {
   "title": "JS Servers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nats_core_jetstream_info{server_jetstream=\"true\"})",
     "legendFormat": "Enabled"
    },
    {
     "expr": "count(nats_core_jetstream_enabled == 1)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "JS HA Assets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_core_jetstream_ha_assets{})",
     "legendFormat": "Enabled"
    }
   ]
  },
  {
   "title": "Meta's Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nats_core_jetstream_cluster_raft_group_replicas * on(server_id) group_left(server_domain, server_cluster,server_name) nats_core_jetstream_info > 0",
     "legendFormat": "{{server_domain}}:{{server_name}}"
    }
   ]
  },
  {
   "title": "Meta's Votes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (server_domain, leader) (nats_core_jetstream_cluster_raft_group_info{raft_group=\"_meta_\"})",
     "legendFormat": "{{leader}}"
    }
   ]
  },
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Cluster Connections",
   "type": "timeseries",
   "description": "Combined current connections",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_core_connection_count{server_cluster=~\"$cluster\"})",
     "legendFormat": "Connections"
    },
    {
     "expr": "sum(nats_core_subs_count{server_cluster=~\"$cluster\"})",
     "legendFormat": "Subscriptions"
    }
   ]
  },
  {
   "title": "Cluster Slow Consumers",
   "type": "timeseries",
   "description": "Combined slow consumers detected per second",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nats_core_slow_consumer_count{server_cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Slow Consumers"
    }
   ]
  },
  {
   "title": "Cluster JetStream API Requests",
   "type": "timeseries",
   "description": "JetStream API requests per second by server (stacked)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nats_core_jetstream_api_requests{cluster_name=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Cluster JetStream API Pending",
   "type": "timeseries",
   "description": "JetStream API requests pending processing (stacked)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nats_core_jetstream_api_pending{cluster_name=~\"$cluster\"}",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Stream Leaders by Server (stacked)",
   "type": "timeseries",
   "description": "Number of streams each server is the leader for (includes R1 streams). The top of the stack is the total unique stream count across the cluster.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "nats_core_jetstream_server_total_stream_leaders{cluster_name=~\"$cluster\"}",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Consumer Leaders by Server (stacked)",
   "type": "timeseries",
   "description": "Number of consumers each server is the leader for (includes R1 consumers). The top of the stack is the total unique consumer count across the cluster.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "nats_core_jetstream_server_total_consumer_leaders{cluster_name=~\"$cluster\"}",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Cluster Message Traffic",
   "type": "timeseries",
   "description": "Aggregate messages across all servers and all connection types: clients, routes, gateways and leafnodes",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nats_core_sent_msgs_count{server_cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(nats_core_recv_msgs_count{server_cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Cluster Network Usage",
   "type": "timeseries",
   "description": "Aggregate network usage across all servers and all connection types: clients, routes, gateways and leafnodes",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(nats_core_sent_bytes{server_cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(nats_core_recv_bytes{server_cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Server Versions",
   "type": "timeseries",
   "description": "Distribution of NATS Server Versions across the cluster",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_core_info{server_cluster=~\"$cluster\"}) by (server_version)",
     "legendFormat": "{{server_version}}"
    }
   ]
  },
  {
   "title": "Cluster RTT",
   "type": "heatmap",
   "description": "RTT times for the cluster as observed from the Surveyor",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "nats_core_rtt_nanoseconds", "legendFormat": "RTT" }
   ]
  },
  {
   "title": "Client Connection Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Connections",
     "type": "timeseries",
     "description": "Point in time view of clients connected to each Server",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nats_core_connection_count{server_cluster=~\"$cluster\"}",
       "legendFormat": "{{server_name}}"
      }
     ]
    },
    {
     "title": "Active Subscriptions",
     "type": "timeseries",
     "description": "Number of subscriptions active on the server",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nats_core_subs_count{server_cluster=~\"$cluster\"}",
       "legendFormat": "{{server_name}}"
      }
     ]
    },
    {
     "title": "Connections per second",
     "type": "timeseries",
     "description": "Connections received by the server in a second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nats_core_total_connection_count{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{server_name}}"
      }
     ]
    },
    {
     "title": "Subscription Delta",
     "type": "timeseries",
     "description": "The difference in subscription count per minute",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(nats_core_subs_count{server_cluster=~\"$cluster\"}[1m])",
       "legendFormat": "{{server_name}}"
      }
     ]
    },
    {
     "title": "Slow Consumers",
     "type": "timeseries",
     "description": "Slow consumers detected by each server",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nats_core_slow_consumer_count{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{server_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gateway Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gateway Bytes Sent",
     "type": "timeseries",
     "description": "Bytes sent for each gateway",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(nats_core_gateway_sent_bytes{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{server_name}} - {{server_cluster}} -> {{server_gateway_name}}"
      }
     ]
    },
    {
     "title": "Gateway Bytes Received",
     "type": "timeseries",
     "description": "Bytes received for each gateway",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(nats_core_gateway_recv_bytes{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{server_name}} - {{server_cluster}} -> {{server_gateway_name}}"
      }
     ]
    },
    {
     "title": "Gateway Messages Sent",
     "type": "timeseries",
     "description": "Messages sent for each gateway",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nats_core_gateway_sent_msgs_count{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{server_name}} - {{server_cluster}} -> {{server_gateway_name}}"
      }
     ]
    },
    {
     "title": "Gateway Messages Received",
     "type": "timeseries",
     "description": "Messages received for each gateway",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nats_core_gateway_recv_msg_count{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{server_name}} - {{server_cluster}} -> {{server_gateway_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Route Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Route Bytes Sent",
     "type": "timeseries",
     "description": "Bytes sent for each route",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(nats_core_route_sent_bytes{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "Server {{server_name}} - Route {{server_route_name}}"
      }
     ]
    },
    {
     "title": "Route Bytes Received",
     "type": "timeseries",
     "description": "Bytes received for each route",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(nats_core_route_recv_bytes{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "Server {{server_name}} - Route {{server_route_name}}"
      }
     ]
    },
    {
     "title": "Route Messages Sent",
     "type": "timeseries",
     "description": "Messages sent for each route",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nats_core_route_sent_msg_count{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "Server {{server_name}} - Route {{server_route_name}}"
      }
     ]
    },
    {
     "title": "Route Messages Received",
     "type": "timeseries",
     "description": "Messages received for each route",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nats_core_route_recv_msg_count{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "Server {{server_name}} - Route {{server_route_name}}"
      }
     ]
    },
    {
     "title": "Cluster Size",
     "type": "timeseries",
     "description": "The number of servers in each cluster",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(nats_core_info{server_cluster=~\"$cluster\"}) by (server_cluster)",
       "legendFormat": "{{server_cluster}}"
      }
     ]
    },
    {
     "title": "Route Pending Data",
     "type": "timeseries",
     "description": "Data in the pending buffers that needs to be sent to remotes",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "nats_core_route_pending_bytes{server_cluster=~\"$cluster\"}",
       "legendFormat": "Server {{server_name}} - Route {{server_route_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Usage Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages Sent to Clients",
     "type": "timeseries",
     "description": "Messages/s sent by servers to client connections (excludes routes, gateways, leafnodes)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nats_core_sent_to_client_msgs_total{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{server_name}}"
      }
     ]
    },
    {
     "title": "Messages Received from Clients",
     "type": "timeseries",
     "description": "Messages/s received by servers from client connections (excludes routes, gateways, leafnodes)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nats_core_recv_from_client_msgs_total{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{server_name}}"
      }
     ]
    },
    {
     "title": "Bytes Sent to Clients",
     "type": "timeseries",
     "description": "Bytes/s sent by servers to client connections (excludes routes, gateways, leafnodes)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(nats_core_sent_to_client_bytes_total{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{server_name}}"
      }
     ]
    },
    {
     "title": "Bytes Received from Clients",
     "type": "timeseries",
     "description": "Bytes/s received by servers from client connections (excludes routes, gateways, leafnodes)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(nats_core_recv_from_client_bytes_total{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{server_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (100% = 1 core)",
     "type": "timeseries",
     "description": "CPU used by the NATS Server process. 100% = 1 core fully utilized.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nats_core_cpu_percentage{server_cluster=~\"$cluster\"}",
       "legendFormat": "{{server_name}}"
      }
     ]
    },
    {
     "title": "Memory (RSS)",
     "type": "timeseries",
     "description": "RSS memory in use by the NATS server process",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "nats_core_mem_bytes{server_cluster=~\"$cluster\"}",
       "legendFormat": "{{server_name}} (usage)"
      },
      {
       "expr": "nats_core_go_memlimit_bytes{server_cluster=~\"$cluster\"}",
       "legendFormat": "{{server_name}} (GOMEMLIMIT)"
      }
     ]
    },
    {
     "title": "CPU Usage (Normalized)",
     "type": "timeseries",
     "description": "CPU used by the NATS Server process normalized by number of cores (% of total machine capacity)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "nats_core_cpu_percentage{server_cluster=~\"$cluster\"} / nats_core_core_count{server_cluster=~\"$cluster\"}",
       "legendFormat": "{{server_name}}"
      }
     ]
    },
    {
     "title": "Memory Usage (% of GOMEMLIMIT)",
     "type": "timeseries",
     "gridPos": { "x": 12, "y": 17, "h": 7, "w": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "nats_core_mem_bytes{server_cluster=~\"$cluster\"} / nats_core_go_memlimit_bytes{server_cluster=~\"$cluster\"} * 100",
       "legendFormat": "{{server_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Surveyor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Expected vs Received",
     "type": "timeseries",
     "description": "The number of NATS Servers expected to reply vs how many replied during a poll",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "nats_survey_expected_count", "legendFormat": "Expected" },
      { "expr": "nats_survey_surveyed_count", "legendFormat": "Responded" }
     ]
    },
    {
     "title": "Cluster RTT per server",
     "type": "timeseries",
     "description": "Cluster wide RTT as calculated from the Surveyor",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      { "expr": "nats_core_rtt_nanoseconds", "legendFormat": "{{server_name}}" }
     ]
    },
    {
     "title": "NATS Reconnects",
     "type": "timeseries",
     "description": "Number of times the surveyor reconnected to the network in a minute",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(nats_survey_nats_reconnects[5m])",
       "legendFormat": "Reconnections"
      }
     ]
    },
    {
     "title": "Poll Time",
     "type": "timeseries",
     "description": "Time it takes the surveyor to gather the statistics from surveyed NATS Servers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": " rate(nats_survey_duration_seconds_sum[5m])\n/\n  rate(nats_survey_duration_seconds_count[5m])",
       "legendFormat": "Poll Time"
      }
     ]
    }
   ]
  }
 ]
}