{
 "title": "Network Usage",
 "tags": [ "surveyor" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prom_ds", "label": "Prometheus Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(nats_core_info, server_cluster)"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(rate(nats_core_sent_bytes{server_cluster=~\"$cluster\"}[$__rate_interval])) + sum(rate(nats_core_recv_bytes{server_cluster=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "Bits/sec"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(rate(nats_core_sent_msgs_count{server_cluster=~\"$cluster\"}[$__rate_interval])) + sum(rate(nats_core_recv_msgs_count{server_cluster=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "Messages/sec"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nats_core_sent_bytes{server_cluster=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Sent"
      },
      {
       "expr": "sum(rate(nats_core_recv_bytes{server_cluster=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Received"
      }
     ]
    },
    {
     "title": "Messages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nats_core_sent_msgs_count{server_cluster=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Sent"
      },
      {
       "expr": "sum(rate(nats_core_recv_msgs_count{server_cluster=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Received"
      }
     ]
    },
    {
     "title": "Bytes Sent",
     "type": "graph",
     "description": "Data sent per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_sent_bytes{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{server_name}}"
      }
     ]
    },
    {
     "title": "Bytes Received",
     "type": "graph",
     "description": "Data received per second",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_recv_bytes{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{server_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages Sent",
     "type": "graph",
     "description": "Messages sent per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_sent_msgs_count{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{server_name}}"
      }
     ]
    },
    {
     "title": "Messages Received",
     "type": "graph",
     "description": "Messages received per second",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_recv_msgs_count{server_cluster=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{server_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Conditions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster RTT",
     "type": "graph",
     "description": "Cluster wide RTT as calculated from the Surveyor",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ns", "label": "RTT" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_rtt_nanoseconds[$__rate_interval])",
       "legendFormat": "{{server_name}}"
      }
     ]
    }
   ]
  }
 ]
}