---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "surveyor.fullname" . }}
  labels:
    {{- include "surveyor.labels" . | nindent 4 }}
stringData:
  SYS.creds: {{ .Values.config.creds | quote }}
